name: base
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - cudatoolkit=10.1
  - pip
  - pip:
    - tensorboard
    - torch===1.4.0
    - pandas
    - pyarrow
    - transformers==2.6